#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: alertmanager
#  namespace: kube-system
#  labels:
#    kubernetes.io/cluster-service: "true"
#    addonmanager.kubernetes.io/mode: EnsureExists
#spec:
#  storageClassName: managed-nfs-storage 
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: "2Gi"
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alertmanager
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      pv: alert
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0003
  namespace: kube-system
  labels:
    pv: alert
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /data/nfs/
    server: 192.168.10.110

